export const TOP_RO_WORDS: ReadonlyArray<string> = [
  'a', 'al', 'altă', 'alt', 'am', 'an', 'apă', 'apoi', 'are', 'asa',
  'au', 'avea', 'azi', 'bine', 'bun', 'bună', 'cale', 'când', 'care', 'cărți',
  'casă', 'caz', 'ce', 'cei', 'cele', 'centru', 'cer', 'chiar', 'cine', 'copil',
  'corp', 'cred', 'cum', 'cuvânt', 'dă', 'da', 'dacă', 'dar', 'dat', 'de',
  'des', 'după', 'două', 'doi', 'drum', 'el', 'ea', 'face', 'fac', 'fără',
  'fel', 'femeie', 'fi', 'fie', 'foarte', 'fost', 'frate', 'fără', 'fugi', 'gând',
  'gândi', 'gata', 'greu', 'gură', 'hai', 'iar', 'iată', 'idee', 'iei', 'încă',
  'între', 'între', 'inima', 'la', 'lăsa', 'lege', 'lega', 'lucru', 'lume', 'lung',
  'mâncare', 'mâine', 'mare', 'mai', 'măsură', 'mama', 'mână', 'mea', 'merg', 'merge',
  'mergea', 'mers', 'mic', 'mine', 'minte', 'minuni', 'mod', 'mult', 'munte', 'nou',
  'noua', 'noi', 'nu', 'om', 'ori', 'orice', 'parc', 'parte', 'pat', 'pe',
  'pentru', 'piatră', 'piaț', 'piață', 'plec', 'pleca', 'poate', 'pod', 'pom', 'porni',
  'punct', 'pune', 'puțin', 'rău', 'risc', 'sat', 'sare', 'sau', 'şcoală', 'scrie',
  'sfârșit', 'soare', 'spre', 'stiu', 'știu', 'sub', 'sunet', 'sus', 'susține', 'suni',
  'tată', 'te', 'timp', 'toți', 'totul', 'tu', 'unde', 'uşa', 'ușă', 'vânt',
  'văd', 'vale', 'vedea', 'vede', 'vis', 'voi', 'vorbi', 'vreo', 'zi', 'zile',
];
